In [2]:
import pandas as pd 

data = pd.read_csv("public_art.csv") 

data.head()

,id,name,title,artist_name,art_type,park,image,neighborhood,council_district,ward,tract,public_works_division,pli_division,police_zone,fire_zone,latitude,longitude
0,812728309,1001,Oakwood Road Monument,NaN,NaN,NaN,NaN,Oakwood,2.0,28.0,4.200356e+10,5.0,28.0,6.0,1-19,40.429192,-80.066225
1,188255168,1002,Rooster Waiting For The Streetcar,James Simon,Modern and Contemporary Art,NaN,NaN,Elliott,2.0,20.0,4.200356e+10,5.0,20.0,6.0,1-17,40.442926,-80.039711
2,2032091917,129,Middle East Memorial Plaque,NaN,War Memorials,NaN,NaN,Central Business District,6.0,1.0,4.200302e+10,6.0,1.0,2.0,1-4,40.438092,-79.996852
3,1447629273,143,L'Enfant,Paul Roger-Bloche,Historic Art,NaN,NaN,Carrick,4.0,29.0,4.200329e+10,3.0,29.0,3.0,4-23,40.388748,-79.986497
4,1935017944,148,Veterans Memorial (Brookline),NaN,War Memorials,Brookline Monument,NaN,Brookline,4.0,19.0,4.200319e+10,5.0,19.0,6.0,4-26,40.391721,-80.016981

In [3]:
data_dict = dict()

i = 0
while i < len(data):
    if data.iloc[i]["neighborhood"] not in data_dict:
        data_dict[data.iloc[i]["neighborhood"]] = 1
    else:
        data_dict[data.iloc[i]["neighborhood"]] = data_dict[data.iloc[i]["neighborhood"]] + 1
    i += 1

print(data_dict)

{'Oakwood': 1, 'Elliott': 3, 'Central Business District': 27, 'Carrick': 3, 'Brookline': 2, 'South Side Slopes': 3, nan: 2, 'Hazelwood': 4, 'Highland Park': 10, 'Squirrel Hill South': 22, 'Regent Square': 2, 'Perry North': 2, 'Beechview': 8, 'Beltzhoover': 3, 'Spring Hill-City View': 4, 'West End': 2, 'Greenfield': 3, 'Shadyside': 6, 'East Allegheny': 2, 'Squirrel Hill North': 2, 'Crawford-Roberts': 3, 'Lincoln-Lemington-Belmar': 2, 'Hays': 1, 'Allegheny Center': 18, 'North Oakland': 1, 'South Side Flats': 10, 'Central Oakland': 5, 'Point Breeze': 3, 'Allegheny West': 1, 'Strip District': 2, 'Mount Washington': 2, 'Brighton Heights': 5, 'Perry South': 1, 'North Shore': 8, 'Upper Hill': 2, 'Garfield': 2, 'Central Lawrenceville': 2, 'Upper Lawrenceville': 1, 'Stanton Heights': 1, 'Duquesne Heights': 3, 'Allentown': 2, 'East Liberty': 1, 'Bloomfield': 1, 'East Carnegie': 1, 'East Hills': 1, 'Lower Lawrenceville': 5, 'Overbrook': 1, 'Polish Hill': 1, 'Sheraden': 1, 'Spring Garden': 2, 'Swisshelm Park': 1, 'Troy Hill': 1, 'Crafton Heights': 1, 'Esplen': 1, 'Knoxville': 1, 'Manchester': 1}